[project]
name = "rubik-tensor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "fire>=0.7.0",
    "numpy>=2.3.1",
]

[dependency-groups]
dev = [
    "mypy>=1.16.1",
    "pre-commit>=4.2.0",
    "ruff>=0.12.0",
]

[tool.uv]
package = true # this ensures that `uv run` doesn't actually build the package; a `make` command is needed to build
