name: Sanity checks
on: [pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - uses: pre-commit/action@v3.0.1

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.3"
        enable-cache: true
    - name: Install project
      run: uv sync --locked --extra torch-cpu
    - name: Run tests
      run: uv run pytest tests/unit
