name: Push to Huggingface Space
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    - name: Push to hub
      env:
        HF_USERNAME: JBAujogue
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        SPACE_NAME: Rubik-Tensor
      run: git push https://HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/HF_USERNAME/SPACE_NAME main
